environment:
  build_version: 1.0.0
  Version: $(build_version)-Beta%APPVEYOR_BUILD_NUMBER%
version: $(build_version)-{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(build_version).0'
  assembly_file_version: '$(build_version).{build}'
  assembly_informational_version: '$(build_version)'
before_build:
 - cmd: nuget restore SimpleRequests.sln
build:
  project: SimpleRequests.sln
  publish_nuget: true
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.tests.dll'
artifacts:
- path: src\**\SimpleRequests*.nupkg
  name: SimpleRequests
image:
- Visual Studio 2022
